name: test
on:
  push:
    branches: [test]
env:
  VITE_COMMIT_SHA: ${{github.sha}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run staging
      - name: Copy index to list
        run: cp dist/index.html dist/list.html
      - name: Copy index to flow
        run: cp dist/index.html dist/flow.html
      - name: Copy index to 404
        run: cp dist/index.html dist/404.html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.4.8
        with:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          REPOSITORY_NAME: batchmode/batchmode.github.io
          BRANCH: main
          FOLDER: dist
          TARGET_FOLDER: dsp-production-overview-test
          CLEAN: true
